payment_test_mode = env("PAYMENT_TEST_MODE","");

if(payment_test_mode===true){
   module.exports = {
      plans:{
         1:{
            chatbot_basic_monthly:{
               plan_id : 1,
               stripe_plan_id:"",
               inr_stripe_plan_id:"",
               successUrl:"",
               cancelUrl : "",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 5,
               document: 1,
               credits : 100,
               characters : 1000,
               members : 0,
               webpages : 10,
               isFree:true,
               recurring_interval:'monthly'
            },
            chatbot_starter_monthly:{
               plan_id : 2,
               stripe_plan_id:"price_1MsiQfSFnJmyrDL86CNgNgZO",
               paddle_plan_id: "pri_01hxeewpz8xjhtp34j0wm879pd",
               inr_stripe_plan_id:"price_1MzES8SFnJmyrDL8N5Elff4E",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot  : 1,
               webpages : 100,
               document : 10,
               credits  : 3 * 1000000,
               characters: 1000000, //1 Million,
               members  : 1,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_essential_monthly:{
               plan_id:3,
               stripe_plan_id:"price_1ND0fASFnJmyrDL8lZM6OINv",
               inr_stripe_plan_id:"price_1ND0fBSFnJmyrDL8inXmnpBG",
               paddle_plan_id: "pri_01hx8yr6qysxyksthk1pvx2396",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot  : 2,
               webpages : 200,
               document : 20,
               credits  : 10 * 1000000,
               characters: 5000000, // 5 Million
               members  : 3,
               is_subscription_trial:true,
               recurring_interval:'monthly'
           },
            chatbot_professional_monthly:{
               plan_id:4,
               stripe_plan_id:"price_1N28lSSFnJmyrDL836Njp6Dm",
               inr_stripe_plan_id:"price_1ND2xtSFnJmyrDL8tojCcf4V",
               paddle_plan_id: "pri_01hx8ysyw8tapp3jrbzgd1zt5p",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 5,
               webpages: 500,
               document: 100,
               credits : 30 * 1000000,
               characters: 10000000, //10 Million
               members : 5,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_growth_monthly:{
               plan_id:103,
               stripe_plan_id:"price_1ONAzsSFnJmyrDL8nTHhnjFj",
               inr_stripe_plan_id:"price_1ONAzsSFnJmyrDL8nTHhnjFj",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot  : 5,
               webpages : 1000,
               document : 200,
               credits  : "50000000/∞",
               characters: 20000000, // 5 Million
               members  : 5,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_advanced_monthly:{
               plan_id:19,
               stripe_plan_id:"price_1OFyt1SFnJmyrDL8c89t5xnH",
               inr_stripe_plan_id:"price_1OFyt1SFnJmyrDL8c89t5xnH",
               paddle_plan_id: "pri_01hx8yw6r3gy1hmdk1grv1k3qj",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages","voice_credits"],
               chatbot : 10,
               webpages : 2000,
               document: 500,
               credits : "100000000/∞",
               characters: 1000000000,
               members : 10,
               voice_credits: 100,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_agency_monthly:{
               plan_id:105,
               stripe_plan_id:"price_1OZvv3SFnJmyrDL8IcGAz5xI",
               inr_stripe_plan_id:"price_1OZvv3SFnJmyrDL8IcGAz5xI",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 10,
               webpages : 5000,
               document: 1000,
               credits : 100000000,
               characters: 100000000,
               members : 10,
               recurring_interval:'monthly',
               use_for : "agency"
            },
           chatbot_elite_monthly:{
            plan_id:5,
            stripe_plan_id:"price_1NE6sFSFnJmyrDL80ckGE6hJ",
            inr_stripe_plan_id:"price_1NE6suSFnJmyrDL89X4wVy7h",
            successUrl:"https://chatbot.yourgpt.ai/payment-success",
            cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
            type : "organization",
            features:["chatbot","document","credits","characters","members","webpages"],
            chatbot : 100000000,
            document: 2000,
            credits : 50000,
            characters : 100000000, // 100 Million
            webpages : 1000,
            members : 20,
            is_subscription_trial:true,
            recurring_interval:'monthly'
         },
         chatbot_eliteNew_monthly:{
            plan_id:6,
            stripe_plan_id:"",
            inr_stripe_plan_id:"",
            successUrl:"https://chatbot.yourgpt.ai/payment-success",
            cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
            type : "organization",
            features:["chatbot","document","credits","characters","members","webpages"],
            chatbot : 0,
            document: 0,
            credits : 0,
            characters: 0,
            webpages : 0,
            members : 0,
            recurring_interval:'monthly'
         },
         chatbot_trial:{
            plan_id : 7,
            stripe_plan_id:'',
            inr_stripe_plan_id:"",
            type : "organization",
            successUrl:"https://chatbot.yourgpt.ai/payment-success",
            cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
            features:["chatbot","document","credits","characters","members","webpages"],
            chatbot : 1,
            document: 5,
            credits : 100000,
            characters : 100000,
            members : 1,
            webpages: 5,
            is_trial:true
         },
            chatbot_starter_yearly:{
               plan_id:8,
               stripe_plan_id:"price_1MsiQPSFnJmyrDL89pyxAmM8",
               inr_stripe_plan_id:"price_1NhTB3SFnJmyrDL8lhPuGO4z",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot : 1,
               webpages: 100,
               document: 10,
               credits : 5 * 1000000 * 12,
               characters: 1000000  * 12, //1 Million
               members : 1,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_advanced_yearly:{
               plan_id:22,
               stripe_plan_id:"price_1PEVlTSFnJmyrDL8QDOADJjm",
               inr_stripe_plan_id:"price_1PEVlTSFnJmyrDL8QDOADJjm",
               paddle_plan_id: "",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages","voice_credits"],
               chatbot : 10,
               webpages : 2000,
               document: 500,
               credits : "100000000/∞",
               characters: 1000000000 * 12,
               members : 10 * 12,
               voice_credits: 100 * 12,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_essential_yearly:{
               plan_id:9,
               stripe_plan_id:"price_1NhTCxSFnJmyrDL8vh7e4rJ8",
               inr_stripe_plan_id:"price_1NhTDfSFnJmyrDL8imGNPJgP",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot  : 2,
               webpages : 200,
               document : 20,
               credits  : 10 * 1000000 * 12,
               characters: 5000000 * 12, // 5 Million
               members  : 3,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_professional_yearly:{
               plan_id:10,
               stripe_plan_id:"price_1NhTFrSFnJmyrDL8ohJlWp2A",
               inr_stripe_plan_id:"price_1NhTGbSFnJmyrDL8Gr1jhuEd",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot  : 5,
               webpages : 500,
               document : 100,
               credits  : 30 * 1000000 * 12,
               characters: 10000000 * 12, //10 Million
               members : 5,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_growth_yearly:{
               plan_id:104,
               stripe_plan_id:"price_1ONAzsSFnJmyrDL8sHcQ7YGo",
               inr_stripe_plan_id:"price_1ONAzsSFnJmyrDL8sHcQ7YGo",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot  : 5,
               webpages : 1000,
               document : 200,
               credits  : "5000000/∞",
               characters: 20000000 * 12, // 20 Million
               members  : 5,
               is_subscription_trial:true,
               recurring_interval:'monthly'
           },
            chatbot_standard_yearly:{
               plan_id:20,
               stripe_plan_id:"price_1NhTCxSFnJmyrDL8vh7e4rJ8",
               inr_stripe_plan_id:"price_1NhTDfSFnJmyrDL8imGNPJgP",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot  : 2,
               webpages : 200,
               document : 20,
               credits  : 10 * 1000000 * 12,
               characters: 5000000 * 12, // 5 Million
               members  : 3,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_exclusive_yearly:{
               plan_id:21,
               stripe_plan_id:"price_1NhTCxSFnJmyrDL8vh7e4rJ8",
               inr_stripe_plan_id:"price_1NhTDfSFnJmyrDL8imGNPJgP",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot  : 2,
               webpages : 200,
               document : 20,
               credits  : 10 * 1000000 * 12,
               characters: 5000000 * 12, // 5 Million
               members  : 3,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
           chatbot_agency_yearly:{
            plan_id:106,
            stripe_plan_id:"price_1OZvwUSFnJmyrDL8gMjlk18d",
            inr_stripe_plan_id:"price_1OZvwUSFnJmyrDL8gMjlk18d",
            successUrl:"https://chatbot.yourgpt.ai/payment-success",
            cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
            type : "organization",
            features:["chatbot","document","credits","characters","members","webpages"],
            chatbot : 10,
            webpages : 5000,
            document: 1000,
            credits : 100000000 * 12,
            characters: 100000000,
            members : 10,
            recurring_interval:'yearly'
            },
            chatbot_prime_standard_yearly:{
               plan_id : 107,
               stripe_plan_id:'price_1PDoBKSFnJmyrDL8VYN9YR79',
               inr_stripe_plan_id:"price_1PDoBKSFnJmyrDL8VYN9YR79",
               paddle_plan_id: "pri_01hx8yyf71dm29sgfwsp57kxdk",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot : 5,
               document: 20,
               credits : "50000000/∞",
               characters: 1000000 * 50, // 50 Million
               webpages : 200,
               members : 3 ,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_prime_exclusive_yearly:{
               plan_id:108,
               stripe_plan_id:"price_1PDoCLSFnJmyrDL8WEneaUmJ",
               inr_stripe_plan_id:"price_1PDoCLSFnJmyrDL8WEneaUmJ",
               paddle_plan_id: "pri_01hx8yzgkhy93ecg5nm03qzxqp",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages", "custom_branding"],
               chatbot : 10,
               document: 200 * 12,
               credits : "200000000/∞",
               characters: 1000000 * 100, // 5 Million
               members : 5,
               webpages : 2000,
               recurring_interval:'yearly',
               is_subscription_trial:true,
               custom_branding: 1
           },
            chat_bot_add_on : {
               query_credit_addon : {
                  plan_id : 1,
                  purpose : ["credits"],
                  stripe_plan_id:"price_1NEB1JSFnJmyrDL8wOvkYHBX",
                  inr_stripe_plan_id:"price_1NEB1JSFnJmyrDL8vSvzMx5G",
                  paddle_plan_id: "pri_01hx96tqg12njfw144kx8jkt02",
                  credits : 2 * 1000000,
                  recurring_interval:'monthly',
                  max_limit : 50
               },
               credit_addon_yearly : {
                  plan_id : 1,
                  purpose : ["credits"],
                  stripe_plan_id:"price_1NhVqZSFnJmyrDL8GEDZOioz",
                  inr_stripe_plan_id:"price_1NhVq1SFnJmyrDL81aseZQz2",
                  credits : 2 * 1000000,
                  recurring_interval:'yearly',
                  max_limit : 50
               },
               agency_credit_addon : {
                  plan_id : 1,
                  purpose : ["credits"],
                  stripe_plan_id:"price_1OaD0JSFnJmyrDL89S9lwvMA",
                  inr_stripe_plan_id:"price_1OaD0JSFnJmyrDL89S9lwvMA",
                  credits : 3.5 * 1000000,
                  recurring_interval:'monthly',
                  max_limit : 50,
                  use_for : "agency"
               },
               agency_credit_addon_yearly : {
                  plan_id : 1,
                  purpose : ["credits"],
                  stripe_plan_id:"price_1OaD0JSFnJmyrDL8zmRtyV47",
                  inr_stripe_plan_id:"price_1OaD0JSFnJmyrDL8zmRtyV47",
                  credits : 3.5 * 1000000,
                  recurring_interval:'yearly',
                  max_limit : 50,
                  use_for : "agency"
               },
               documents_character_addon : {
                  plan_id : 1,
                  purpose : ["document","characters"],
                  stripe_plan_id:"price_1OaCK3SFnJmyrDL83gqgkXpK",
                  inr_stripe_plan_id:"price_1OaCK3SFnJmyrDL83gqgkXpK",
                  paddle_plan_id: "pri_01hxef3yr3cmyskx88nj26n3ny",
                  document : 100,
                  characters: 10 * 1000000,
                  recurring_interval:'monthly',
                  max_limit : 20
               },
               documents_character_addon_yearly : {
                  plan_id : 1,
                  purpose : ["document","characters"],
                  stripe_plan_id:"price_1OaCtuSFnJmyrDL8BhxOOizd",
                  inr_stripe_plan_id:"price_1OaCtuSFnJmyrDL8BhxOOizd",
                  document : 100,
                  characters: 10 * 1000000,
                  recurring_interval:'yearly',
                  max_limit : 20
               },
               custom_branding_addon : {
                  plan_id : 1,
                  purpose : ["custom_branding"],
                  stripe_plan_id:"price_1OJwJPSFnJmyrDL8zyTIVFi0",
                  inr_stripe_plan_id:"price_1OJwJPSFnJmyrDL8zyTIVFi0",
                  paddle_plan_id: "pri_01hxef98x5zpjgdkxzbc9txbap",
                  custom_branding : 1,
                  recurring_interval:'monthly',
                  max_limit : 1
               },
               custom_branding_addon_yearly : {
                  plan_id : 1,
                  purpose : ["custom_branding"],
                  stripe_plan_id:"price_1OKKTQSFnJmyrDL8Q94Que1D",
                  inr_stripe_plan_id:"price_1OKKTQSFnJmyrDL8Q94Que1D",
                  custom_branding : 1,
                  recurring_interval:'yearly',
                  max_limit : 1
               },
               voice_addon : {
                  plan_id : 1,
                  purpose : ["voice_credits"],
                  stripe_plan_id:"price_1OwNVySFnJmyrDL8YHNfqEeD",
                  inr_stripe_plan_id:"price_1OwNVySFnJmyrDL8YHNfqEeD",
                  paddle_plan_id: "pri_01hxefaxbzcg9n0e2t0d1zb0vh",
                  voice_credits : 100,
                  recurring_interval:'monthly',
                  max_limit : 1000
               },
               voice_addon_yearly : {
                  plan_id : 1,
                  purpose : ["voice_credits"],
                  stripe_plan_id:"price_1OwNVySFnJmyrDL8QeA3qicz",
                  inr_stripe_plan_id:"price_1OwNVySFnJmyrDL8QeA3qicz",
                  voice_credits : 100,
                  recurring_interval:'yearly',
                  max_limit : 1000
               },
               extra_chatbot_addon : {
                  plan_id : 1,
                  purpose : ["chatbot"],
                  stripe_plan_id:"price_1OJwKwSFnJmyrDL8qpmY3cJK",
                  inr_stripe_plan_id:"price_1OJwKwSFnJmyrDL8qpmY3cJK",
                  paddle_plan_id: "pri_01hxef74g48n5580aebmr1vvvd",
                  chatbot : 1,
                  recurring_interval:'monthly',
                  max_limit : 20
               },
               extra_chatbot_addon_yearly : {
                  plan_id : 1,
                  purpose : ["chatbot"],
                  stripe_plan_id:"price_1OKKVFSFnJmyrDL8UOe82h9A",
                  inr_stripe_plan_id:"price_1OKKVFSFnJmyrDL8UOe82h9A",
                  chatbot : 1,
                  recurring_interval:'yearly',
                  max_limit : 20
               },
               custom_domain_addon : {
                  plan_id : 1,
                  purpose : ["custom_domain"],
                  stripe_plan_id:"price_1OJwLxSFnJmyrDL8lD14RzBi",
                  inr_stripe_plan_id:"price_1OJwLxSFnJmyrDL8lD14RzBi",
                  paddle_plan_id: "pri_01hxef5k0ddwd8kxjtafdf2ny7",
                  custom_domain : 1,
                  recurring_interval:'monthly',
                  max_limit : 1
               },
               custom_domain_addon_yearly : {
                  plan_id : 1,
                  purpose : ["custom_domain"],
                  stripe_plan_id:"price_1OKKXDSFnJmyrDL8iDxXItbA",
                  inr_stripe_plan_id:"price_1OKKXDSFnJmyrDL8iDxXItbA",
                  custom_domain : 1,
                  recurring_interval:'yearly',
                  max_limit : 1
               },
               webpages_addon : {
                  plan_id : 1,
                  purpose : ["webpages","characters"],
                  stripe_plan_id:"price_1OaCMeSFnJmyrDL8gVLHlFAa",
                  inr_stripe_plan_id:"price_1OaCMeSFnJmyrDL8gVLHlFAa",
                  paddle_plan_id : "pri_01hxef2edrwq0916h3jjks6rs1",
                  webpages : 100,
                  characters: 10 * 1000000,
                  recurring_interval:'monthly',
                  max_limit : 20
               },
               webpages_addon_yearly : {
                  plan_id : 1,
                  purpose : ["webpages","characters"],
                  stripe_plan_id:"price_1OaCrkSFnJmyrDL814ephxqF",
                  inr_stripe_plan_id:"price_1OaCrkSFnJmyrDL814ephxqF",
                  webpages : 100,
                  characters: 10 * 1000000,
                  recurring_interval:'yearly',
                  max_limit : 20
               }
            },
         },
         2:{
            qa_basic_trial:{
               plan_id : 11,
               stripe_plan_id:"",
               inr_stripe_plan_id:"",
               successUrl:"",
               cancelUrl : "",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 1,
               document : 2,
               credits : 30,
               characters: 100000, //100K 
               is_trial:true,
               recurring_interval:'monthly'
            },
            qa_starter_monthly:{
               plan_id : 7,
               stripe_plan_id:"price_1ND2mtSFnJmyrDL8mfIbQYH6",
               inr_stripe_plan_id:"price_1ND2mSSFnJmyrDL87J8ujfEA",
               successUrl:"https://qamaster.yourgpt.ai/payment-success",
               cancelUrl : "https://qamaster.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 1,
               document : 10,
               credits : 500,
               characters: 1000000, //1 Million
               // is_trial:true,
               recurring_interval:'monthly'
            },
            qa_essential_monthly:{
               plan_id : 8,
               stripe_plan_id:"price_1ND0q9SFnJmyrDL8ivvX0vaP",
               inr_stripe_plan_id:"price_1ND0q9SFnJmyrDL8eOft2ZMe",
               successUrl:"https://qamaster.yourgpt.ai/payment-success",
               cancelUrl : "https://qamaster.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 3,
               document : 30,
               credits : 3000,
               characters: 3000000,//3 Million,
               recurring_interval:'monthly'
            },
            qa_professional_monthly:{
               plan_id:9,
               stripe_plan_id:"price_1ND2nnSFnJmyrDL8H5fZOOQd",
               inr_stripe_plan_id:"price_1ND2o0SFnJmyrDL8VWj3bCdU",
               successUrl:"https://qamaster.yourgpt.ai/payment-success",
               cancelUrl : "https://qamaster.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 10,
               document : 150,
               credits:10000,
               characters: 10000000, //10 Million,
               recurring_interval:'monthly'
            },
            qa_elite_monthly:{
               plan_id:10,
               stripe_plan_id:"price_1NBbusSFnJmyrDL8jjtYyJSH",
               inr_stripe_plan_id:"price_1NBcPGSFnJmyrDL8JKnUfOps",
               successUrl:"https://qamaster.yourgpt.ai/payment-success",
               cancelUrl : "https://qamaster.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 100000,
               document : 500,
               credits : 50000,
               characters: 100000000,
               recurring_interval:'monthly'
            },
            qa_add_on : {
               add_on_1 : {
                  plan_id : 1,
                  stripe_plan_id:"price_1NEB1JSFnJmyrDL8wOvkYHBX",
                  inr_stripe_plan_id:"price_1NEB1JSFnJmyrDL8vSvzMx5G",
                  workspace : 1,
                  document : 50,
                  credits : 500,
                  characters: 10000,
               },
               add_on_2 : {
                  plan_id : 2,
                  stripe_plan_id:"price_1NEB1JSFnJmyrDL8wOvkYHBX",
                  inr_stripe_plan_id:"price_1NEB1JSFnJmyrDL8vSvzMx5G",
                  workspace : 1,
                  document : 100,
                  credits : 1000,
                  characters: 100000, 
               }
            }
         },
         3:{
            tuneup_professional_yearly:{
               plan_id : 14,
               stripe_plan_id:'price_1NkiTHSFnJmyrDL8yMSXaSJV',
               inr_stripe_plan_id:"price_1NkiTHSFnJmyrDL88lfRiKFj",
               features:["members"],
               successUrl:"https://tuneup.yourgpt.ai/payment-success",
               cancelUrl : "https://tuneup.yourgpt.ai/payment-error",
               type      : "organization",
               members   : 50
            }
         },
         4:{
            llmspark_free_monthly:{
               plan_id:16,
               stripe_plan_id:"",
               successUrl:"",
               cancelUrl : "",
               type : "organization",
               features:["workspace","webpages","document","api_calls","members"],
               workspace : 1,
               webpages  : 50, 
               document  : 5,
               api_calls : 500,
               members   : 3,
               isFree:true,
               recurring_interval:'monthly'
            },
            llmspark_standard_monthly:{
               plan_id:17,
               stripe_plan_id:"price_1O1nMiSFnJmyrDL8f7PUrAUs",
               successUrl:"https://llmspark.yourgpt.ai/payment-success",
               cancelUrl : "https://llmspark.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","webpages","document","api_calls","members"],
               workspace : 2,
               webpages  : 500, 
               document  : 100,
               api_calls : 10000,
               members : 5,
               recurring_interval:'monthly'
            },
            llmspark_professional_monthly:{
               plan_id:18,
               stripe_plan_id:"price_1O1nNrSFnJmyrDL8oP2li1jE",
               successUrl:"https://llmspark.yourgpt.ai/payment-success",
               cancelUrl : "https://llmspark.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","webpages","document","api_calls","members"],
               workspace : 5 , 
               webpages  : 2000, 
               document  : 200,
               api_calls : 50000,
               members   : 10,
               recurring_interval:'monthly'
            }
         },
         5:{
            basic:{
               document_limit:1,
               query_limit:2
               },
               standard_monthly:{
               plan_id:'price_1MsiQfSFnJmyrDL86CNgNgZO',
               document_limit:2,
               query_limit:2,
               inr_plan_id:"price_1MzES8SFnJmyrDL8N5Elff4E",
               },
               growth_monthly:{
               plan_id:'price_1MsiO5SFnJmyrDL8AfTIPyl1',
               document_limit:2,
               query_limit:3,
               inr_plan_id:"price_1MzETGSFnJmyrDL8e7AbYMeS",
               },
               professional_monthly:{
                  plan_id:"price_1MwfmmSFnJmyrDL83cjjAgEF",
                  document_limit:300000,
                  query_limit:400000,
                  inr_plan_id:"price_1MzDJHSFnJmyrDL8WgDwIn4V",
               },
               elite_monthly:{
                  plan_id:"",
                  document_limit:4,
                  query_limit:5
               }
         },
         6:{
            basic:{
               document_limit:1,
               query_limit:2
               },
               standard_monthly:{
               plan_id:'price_1MsiQfSFnJmyrDL86CNgNgZO',
               document_limit:2,
               query_limit:2,
               inr_plan_id:"price_1MzES8SFnJmyrDL8N5Elff4E",
               },
               growth_monthly:{
               plan_id:'price_1MsiO5SFnJmyrDL8AfTIPyl1',
               document_limit:2,
               query_limit:3,
               inr_plan_id:"price_1MzETGSFnJmyrDL8e7AbYMeS",
               },
               professional_monthly:{
                  plan_id:"price_1MwfmmSFnJmyrDL83cjjAgEF",
                  document_limit:300000,
                  query_limit:400000,
                  inr_plan_id:"price_1MzDJHSFnJmyrDL8WgDwIn4V",
               },
               elite_monthly:{
                  plan_id:"",
                  document_limit:4,
                  query_limit:5
               }
         }
      }
   }
}else{
   module.exports = {
      plans:{
         1:{
            chatbot_basic_monthly:{
               plan_id : 1,
               stripe_plan_id:'',
               inr_stripe_plan_id:"",
               type : "organization",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 1,
               document: 1,
               credits : 100 * 1000,
               characters : 1000,
               members : 0,
               webpages : 50,
               isFree:true,
               recurring_interval:'monthly'
            },
            chatbot_starter_monthly:{
               plan_id : 2,
               stripe_plan_id:'price_1Mqy5CSFnJmyrDL8BGMJPMFP',
               inr_stripe_plan_id:"price_1MzEVcSFnJmyrDL8x5veZxHm",
               paddle_plan_id: "pri_01hxeffh36pb8jxyyjn9xrsm0g",
               type : "organization",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 1,
               document: 10,
               credits : 3 *  1000000,
               characters: 10 * 1000000, //10 Million,
               members : 1,
               webpages : 100,
               // is_trial : true,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_essential_monthly:{
               plan_id : 3,
               stripe_plan_id:'price_1ND0fhSFnJmyrDL8TGaS0nH5',
               inr_stripe_plan_id:"price_1ND0fhSFnJmyrDL8EfLFVNwl",
               paddle_plan_id: "pri_01hx8ww1gyx7eg5jb2mzs74m0h",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 2,
               document: 20,
               credits : 10 * 1000000,
               characters: 30 * 1000000, // 5 Million
               members : 3,
               webpages : 200,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_professional_monthly:{
               plan_id : 4,
               stripe_plan_id:'price_1N27OjSFnJmyrDL82uhGJ9AJ',
               inr_stripe_plan_id:"price_1ND2tdSFnJmyrDL8VH4FStuM",
               paddle_plan_id: "pri_01hx8wxtqqbbq5s0j96xhyvxwp",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 5,
               document: 100,
               credits : 30 * 1000000,
               characters: 30 * 1000000, //10 Million
               members : 10,
               webpages : 500,
               is_subscription_trial:true,
              recurring_interval:'monthly'
            },
            chatbot_elite_monthly:{
               plan_id:6,
               stripe_plan_id:"price_1NE71gSFnJmyrDL8hwiNdjlo",
               inr_stripe_plan_id:"price_1NE71xSFnJmyrDL8UWMvRlnf",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot : 100000000,
               document: 2000,
               credits : 50000,
               characters : 100000000, // 100 Million
               webpages : 1000,
               members : 20,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_eliteNew_monthly:{
               plan_id:5,
               stripe_plan_id:"",
               inr_stripe_plan_id:"",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot : 0,
               document: 0,
               credits : 0,
               characters : 0,
               webpages : 0,
               members : 0,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_advanced_monthly:{
               plan_id:19,
               stripe_plan_id:"price_1OItlaSFnJmyrDL8AWLDuaQV",
               inr_stripe_plan_id:"price_1OItlaSFnJmyrDL8AWLDuaQV",
               paddle_plan_id: "pri_01hx8wyywpb27ksyeqks111ygx",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages","voice_credits"],
               chatbot : 10,
               webpages : 2000,
               document: 500,
               credits : "100000000/∞",
               characters: 1000000000,
               members : 10,
               voice_credits: 100,
               is_subscription_trial:true,
               recurring_interval:'monthly'
            },
            chatbot_agency_monthly:{
               plan_id:105,
               stripe_plan_id:"price_1OZw23SFnJmyrDL8lwlukFP1",
               inr_stripe_plan_id:"price_1OZw23SFnJmyrDL8lwlukFP1",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 10,
               webpages : 5000,
               document:  500,
               credits : 100000000,
               characters: 100000000,
               members : 10,
               recurring_interval:'monthly',
               use_for : "agency"
            },
            chatbot_trial:{
               plan_id : 7,
               stripe_plan_id:'',
               inr_stripe_plan_id:"",
               type : "organization",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 1,
               document: 5,
               credits : 50 * 1000,
               members : 1,
               webpages: 10,
               characters : 1000000,
               is_trial:true
            },
            chatbot_growth_monthly:{
               plan_id:103,
               stripe_plan_id:"price_1ON9OoSFnJmyrDL8FTIkZl4j",
               inr_stripe_plan_id:"price_1ON9OoSFnJmyrDL8FTIkZl4j",
               paddle_plan_id: "pri_01hxeg4q64sd1zxrtvzr2crzq5",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 5,
               document: 200,
               credits : "50000000/∞",
               characters: 5000000, // 5 Million
               members : 5,
               webpages : 1000,
               is_subscription_trial:true,
               recurring_interval:'monthly'
           },
            chat_bot_add_on : {
               query_credit_addon : {
                  plan_id : 1,
                  purpose : ["credits"],
                  stripe_plan_id:"price_1NSdWYSFnJmyrDL8T6ksAsTj",
                  inr_stripe_plan_id:"price_1NSdWYSFnJmyrDL8Nncvw6Kn",
                  paddle_plan_id: "pri_01j41q0mwbayfzz8j3nt83v55x",
                  credits : 2 * 1000000,
                  recurring_interval:'monthly',
                  max_limit : 50
               },
               credit_addon_yearly : {
                  plan_id : 2,
                  purpose : ["credits"],
                  stripe_plan_id:"price_1Ngl9mSFnJmyrDL88fLsICRI",
                  inr_stripe_plan_id:"price_1NglA6SFnJmyrDL8vt3IUUoI",
                  paddle_plan_id: "pri_01j41q1m8dgc8n0na62vrxvc4z",
                  credits : 2 * 1000000,
                  recurring_interval:'yearly',
                  max_limit : 50
               },
               agency_credit_addon : {
                  plan_id : 1,
                  purpose : ["credits"],
                  stripe_plan_id:"price_1OaCy3SFnJmyrDL8iRziEmdI",
                  inr_stripe_plan_id:"price_1OaCy3SFnJmyrDL8iRziEmdI",
                  paddle_plan_id: "pri_01j41q0mwbayfzz8j3nt83v55x",
                  credits : 3.5 * 1000000,
                  recurring_interval:'monthly',
                  max_limit : 50,
                  use_for : "agency"
               },
               agency_credit_addon_yearly : {
                  plan_id : 1,
                  purpose : ["credits"],
                  stripe_plan_id:"price_1OaCy3SFnJmyrDL8dyCnL5vc",
                  inr_stripe_plan_id:"price_1OaCy3SFnJmyrDL8dyCnL5vc",
                  paddle_plan_id: "pri_01j41q1m8dgc8n0na62vrxvc4z",
                  credits : 3.5 * 1000000,
                  recurring_interval:'yearly',
                  max_limit : 50,
                  use_for : "agency"
               },
               documents_character_addon : {
                  plan_id : 1,
                  purpose : ["document","characters"],
                  stripe_plan_id:"price_1OaCXBSFnJmyrDL8srsvyLaT",
                  inr_stripe_plan_id:"price_1OaCXBSFnJmyrDL8srsvyLaT",
                  paddle_plan_id: "pri_01hxeftjyemab5g34csa7zbt3d",
                  document : 50,
                  characters: 10 * 1000000,
                  recurring_interval:'monthly',
                  max_limit : 20
               },
               documents_character_addon_yearly : {
                  plan_id : 1,
                  purpose : ["document","characters"],
                  stripe_plan_id:"price_1OaCYXSFnJmyrDL8NtrSc6sr",
                  inr_stripe_plan_id:"price_1OaCYXSFnJmyrDL8NtrSc6sr",
                  paddle_plan_id: "pri_01hxegkp9n2r3mcfpga7bk02xr",
                  document : 50,
                  characters: 10 * 1000000,
                  recurring_interval:'yearly',
                  max_limit : 20
               },
               custom_branding_addon : {
                  plan_id : 1,
                  purpose : ["custom_branding"],
                  stripe_plan_id:"price_1OJwNvSFnJmyrDL8NH92ZkGv",
                  inr_stripe_plan_id:"price_1OJwNvSFnJmyrDL8NH92ZkGv",
                  paddle_plan_id: "pri_01hxeg0qsjwypzzmsc15qjd8mf",
                  custom_branding : 1,
                  recurring_interval:'monthly',
                  max_limit : 1
               },
               custom_branding_addon_yearly : {
                  plan_id : 1,
                  purpose : ["custom_branding"],
                  stripe_plan_id:"price_1OKaBsSFnJmyrDL8uwdk49If",
                  inr_stripe_plan_id:"price_1OKaBsSFnJmyrDL8uwdk49If",
                  paddle_plan_id: "pri_01hxegs5exmwww6g3ypjfnc5gt",
                  custom_branding : 1,
                  recurring_interval:'yearly',
                  max_limit : 1
               },
               extra_chatbot_addon : {
                  plan_id : 1,
                  purpose : ["chatbot"],
                  stripe_plan_id:"price_1OJwPGSFnJmyrDL8MKr7Uw5h",
                  inr_stripe_plan_id:"price_1OJwPGSFnJmyrDL8MKr7Uw5h",
                  paddle_plan_id: "pri_01hxefxpskjhcw2asdy5c3e5jp",
                  chatbot : 1,
                  recurring_interval:'monthly',
                  max_limit : 20
               },
               extra_chatbot_addon_yearly : {
                  plan_id : 1,
                  purpose : ["chatbot"],
                  stripe_plan_id:"price_1OKa9CSFnJmyrDL8FXLDj8pq",
                  inr_stripe_plan_id:"price_1OKa9CSFnJmyrDL8FXLDj8pq",
                  paddle_plan_id: "pri_01hxegqe8ayy8bxyh2cqsb7sar",
                  chatbot : 1,
                  recurring_interval:'yearly',
                  max_limit : 20
               },
               custom_domain_addon : {
                  plan_id : 1,
                  purpose : ["custom_domain"],
                  stripe_plan_id:"price_1OJwQISFnJmyrDL85iCtrVQ1",
                  inr_stripe_plan_id:"price_1OJwQISFnJmyrDL85iCtrVQ1",
                  paddle_plan_id: "pri_01hxefw0txv19a4z3zgaz7gb96",
                  custom_domain : 1,
                  recurring_interval:'monthly',
                  max_limit : 1
               },
               custom_domain_addon_yearly : {
                  plan_id : 1,
                  purpose : ["custom_domain"],
                  stripe_plan_id:"price_1OKa72SFnJmyrDL82l7wCjPt",
                  inr_stripe_plan_id:"price_1OKa72SFnJmyrDL82l7wCjPt",
                  paddle_plan_id: "pri_01hxegnrst6pd198r2xza2geds",
                  custom_domain : 1,
                  recurring_interval:'yearly',
                  max_limit : 1
               },
               webpages_addon : {
                  plan_id : 1,
                  purpose : ["webpages","characters"],
                  stripe_plan_id:"price_1OaCbSSFnJmyrDL8Z5Wjtjha",
                  inr_stripe_plan_id:"price_1OaCbSSFnJmyrDL8Z5Wjtjha",
                  paddle_plan_id: "pri_01hxefm5e7anc9rk3z45k5ay1z",
                  webpages : 100,
                  characters: 10 * 1000000,
                  recurring_interval:'monthly',
                  max_limit : 20
               },
               webpages_addon_yearly : {
                  plan_id : 1,
                  purpose : ["webpages","characters"],
                  stripe_plan_id:"price_1OaCbTSFnJmyrDL836PiLQu2",
                  inr_stripe_plan_id:"price_1OaCbTSFnJmyrDL836PiLQu2",
                  paddle_plan_id: "pri_01hxegfxwvtbnq1fhqrqmxgxnw",
                  webpages : 100,
                  characters: 10 * 1000000,
                  recurring_interval:'yearly',
                  max_limit : 20
               },
               voice_addon : {
                  plan_id : 1,
                  purpose : ["voice_credits"],
                  stripe_plan_id:"price_1OwNaRSFnJmyrDL8QAPCj2Ea",
                  inr_stripe_plan_id:"price_1OwNaRSFnJmyrDL8QAPCj2Ea",
                  paddle_plan_id: "pri_01hxeg2ggwtkpt48absman5qp8",
                  voice_credits : 100,
                  recurring_interval:'monthly',
                  max_limit : 1000
               },
               voice_addon_yearly : {
                  plan_id : 1,
                  purpose : ["voice_credits"],
                  stripe_plan_id:"price_1OwNaRSFnJmyrDL83uzLraSc",
                  inr_stripe_plan_id:"price_1OwNaRSFnJmyrDL83uzLraSc",
                  paddle_plan_id: "pri_01hxegvp4xhvvbh1ft8tqvn9b5",
                  voice_credits : 100,
                  recurring_interval:'yearly',
                  max_limit : 1000
               },
            },
            chatbot_starter_yearly:{
               plan_id : 11,
               stripe_plan_id:'price_1NiYW4SFnJmyrDL8GJTutCIn',
               inr_stripe_plan_id:"price_1NiYXiSFnJmyrDL842Fwbd21",
               paddle_plan_id: "pri_01hxegeh1kxp5y1pe2mst0h3hf",
               type : "organization",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot : 1,
               document: 10,
               credits : 3 * 1000000 * 12,
               characters: 1000000  * 12, //1 Million
               webpages : 100,
               members : 1,
               is_subscription_trial:true,
               recurring_interval:'yearly'
               // is_trial : true
            },
            chatbot_essential_yearly:{
               plan_id : 12,
               stripe_plan_id:'price_1NiYdmSFnJmyrDL8m02Jn6ic',
               inr_stripe_plan_id:"price_1NiYeKSFnJmyrDL8Wf2Wl7aE",
               paddle_plan_id: "pri_01hxegc26ve5mx7k1kzbcq4asy",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot : 2,
               document: 20,
               credits : 10 * 1000000 * 12,
               characters: 5000000 * 12, // 5 Million
               webpages : 200,
               members : 3,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_advanced_yearly:{
               plan_id: 20,
               stripe_plan_id:"price_1PEVI4SFnJmyrDL8iYaYlwcK",
               inr_stripe_plan_id:"price_1PEVI4SFnJmyrDL8iYaYlwcK",
               paddle_plan_id: "",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages","voice_credits"],
               chatbot : 10,
               webpages : 2000,
               document: 500,
               credits : "100000000/∞",
               characters: 1000000000 * 12,
               members : 10 * 12,
               voice_credits: 100 * 12,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_professional_yearly:{
               plan_id : 13,
               stripe_plan_id:'price_1NiYfdSFnJmyrDL8eZr83Wwv',
               inr_stripe_plan_id:"price_1NiYh7SFnJmyrDL8tM3HsZ4W",
               paddle_plan_id: "pri_01hxegaqhmhkj49vdjd62kfwra",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","webpages","members"],
               chatbot : 5,
               document: 100,
               credits : 30 * 1000000,
               characters: 10000000, //10 Million
               webpages : 500,
               members : 10,
               is_subscription_trial:true,
               recurring_interval:'yearly'
            },
            chatbot_growth_yearly:{
               plan_id:104,
               stripe_plan_id:"price_1ON9OoSFnJmyrDL8HcC8QV07",
               inr_stripe_plan_id:"price_1ON9OoSFnJmyrDL8HcC8QV07",
               paddle_plan_id: "pri_01hxeg61gm3j5jt788vrrzqz6h",
               successUrl:"https://chatbot.yourgpt.ai/payment-success",
               cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
               type : "organization",
               features:["chatbot","document","credits","characters","members","webpages"],
               chatbot : 5,
               document: 200,
               credits : "600000000/∞",
               characters: 5000000, // 5 Million
               members : 5,
               webpages : 1000,
               is_subscription_trial:true,
               recurring_interval:'monthly'
           },
           chatbot_prime_standard_yearly:{
            plan_id : 107,
            stripe_plan_id:'price_1PDoDcSFnJmyrDL8y52apDcd',
            inr_stripe_plan_id:"price_1PDoDcSFnJmyrDL8y52apDcd",
            paddle_plan_id: "pri_01hx8xekc0tpt34nx83ptkefnd",
            successUrl:"https://chatbot.yourgpt.ai/payment-success",
            cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
            type : "organization",
            features:["chatbot","document","credits","characters","webpages","members"],
            chatbot : 5,
            document: 100,
            credits : "50000000/∞",
            characters: 1000000 * 50, // 50 Million
            webpages : 500,
            members : 5,
            is_subscription_trial:true,
            recurring_interval:'yearly'
         },
         chatbot_prime_exclusive_yearly:{
            plan_id:108,
            stripe_plan_id:"price_1PQTztSFnJmyrDL8X7PJN1fm",
            inr_stripe_plan_id:"price_1PQTztSFnJmyrDL8X7PJN1fm",
            paddle_plan_id: "pri_01hx8xbv2ezwwq3c4e6w6q30ye",
            successUrl:"https://chatbot.yourgpt.ai/payment-success",
            cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
            type : "organization",
            features:["chatbot","document","credits","characters","members","webpages", "custom_branding","voice_credits"],
            chatbot : 10,
            document: 200,
            credits : "200000000/∞",
            characters: 1000000 * 100, // 5 Million
            members : 10,
            webpages : 2000,
            voice_credits: 100,
            recurring_interval:'yearly',
            is_subscription_trial:true,
            custom_branding: 1
        },
           chatbot_agency_yearly:{
            plan_id:106,
            stripe_plan_id:"price_1OZw23SFnJmyrDL8vm2RyWUZ",
            inr_stripe_plan_id:"price_1OZw23SFnJmyrDL8vm2RyWUZ",
            successUrl:"https://chatbot.yourgpt.ai/payment-success",
            cancelUrl : "https://chatbot.yourgpt.ai/payment-error",
            type : "organization",
            features:["chatbot","document","credits","characters","members","webpages"],
            chatbot : 10,
            webpages: 5000,
            document: 1000,
            credits : 100000000 * 12,
            characters: 100000000,
            members : 10,
            recurring_interval:'yearly'
            },
         },
         2:{
            qa_basic_trial:{
               plan_id : 11,
               stripe_plan_id:"",
               inr_stripe_plan_id:"",
               successUrl:"",
               cancelUrl : "",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 1,
               document : 2,
               credits : 30,
               characters: 100000, //100K 
               is_trial:true,
               recurring_interval:'monthly'
            },
            qa_starter_monthly:{
               plan_id : 7,
               stripe_plan_id:"price_1ND2LUSFnJmyrDL8IRZPx01U",
               inr_stripe_plan_id:"price_1ND2LjSFnJmyrDL8UywvPVoO",
               successUrl:"https://qamaster.yourgpt.ai/payment-success",
               cancelUrl : "https://qamaster.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 1,
               document : 10,
               credits : 500,
               characters: 1000000, //1 Million
               // is_trial:true,
            },
            qa_essential_monthly:{
               plan_id : 8,
               stripe_plan_id:"price_1ND0qsSFnJmyrDL8dDhw7asF",
               inr_stripe_plan_id:"price_1ND0qsSFnJmyrDL8thrzymHa",
               successUrl:"https://qamaster.yourgpt.ai/payment-success",
               cancelUrl : "https://qamaster.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 3,
               document : 30,
               credits : 3000,
               characters: 3000000,//3 Million
            },
            qa_professional_monthly:{
               plan_id:9,
               stripe_plan_id:"price_1ND2ISSFnJmyrDL8oyMMsdXi",
               inr_stripe_plan_id:"price_1ND2JiSFnJmyrDL8HRna6KjB",
               successUrl:"https://qamaster.yourgpt.ai/payment-success",
               cancelUrl : "https://qamaster.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 10,
               document : 150,
               credits:10000,
               characters: 10000000, //10 Million
            },
            qa_elite_monthly:{
               plan_id:10,
               stripe_plan_id:"price_1NBbvUSFnJmyrDL8uZxsvZjr",
               inr_stripe_plan_id:"price_1NBcZlSFnJmyrDL8GlNySHNG",
               successUrl:"https://qamaster.yourgpt.ai/payment-success",
               cancelUrl : "https://qamaster.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","document","credits","characters"],
               workspace : 100000,
               document : 500,
               credits : 50000,
               characters: 100000000, //100 Million
            }
         },
         3:{
            tuneup_professional_yearly:{
               plan_id : 14,
               stripe_plan_id:'price_1NkikbSFnJmyrDL8q0ewwkno',
               inr_stripe_plan_id:"price_1NkikbSFnJmyrDL8Em7ixjrx",
               features:["members"],
               successUrl:"https://tuneup.yourgpt.ai/payment-success",
               cancelUrl : "https://tuneup.yourgpt.ai/payment-error",
               type : "organization",
               members:50,
            }
         },
         4:{
            llmspark_free_monthly:{
               plan_id:16,
               stripe_plan_id:"",
               successUrl:"",
               cancelUrl : "",
               type : "organization",
               features:["workspace","webpages","document","api_calls","members"],
               workspace : 1,
               webpages  : 50, 
               document  : 5,
               api_calls : 500,
               members   : 3,
               isFree:true,
               recurring_interval:'monthly'
            },
            llmspark_standard_monthly:{
               plan_id:17,
               stripe_plan_id:"price_1OET6WSFnJmyrDL8CnQE2gw5",
               successUrl:"https://llmspark.yourgpt.ai/payment-success",
               cancelUrl : "https://llmspark.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","webpages","document","api_calls","members"],
               workspace : 2,
               webpages  : 500, 
               document  : 100,
               api_calls : 10000,
               members : 5,
               recurring_interval:'monthly'
            },
            llmspark_professional_monthly:{
               plan_id:18,
               stripe_plan_id:"price_1OETViSFnJmyrDL84hW3GJhR",
               successUrl:"https://llmspark.yourgpt.ai/payment-success",
               cancelUrl : "https://llmspark.yourgpt.ai/payment-error",
               type : "organization",
               features:["workspace","webpages","document","api_calls","members"],
               workspace : 5 , 
               webpages  : 2000, 
               document  : 200,
               api_calls : 50000,
               members   : 10,
               recurring_interval:'monthly'
            }
         },
         5:{
            basic:{
               document_limit:10,
               query_limit:1000
              },
              standard_monthly:{
               plan_id:"price_1MsiQfSFnJmyrDL86CNgNgZO",
               document_limit:50,
               query_limit:10000,
               inr_plan_id:"price_1MzEVcSFnJmyrDL8x5veZxHm",
              },
              growth_monthly:{
               plan_id:"price_1MsiO5SFnJmyrDL8AfTIPyl1",
               document_limit:250,
               query_limit:50000,
               inr_plan_id:"price_1MzEWFSFnJmyrDL8sGi2XGq2",
              },
              professional_monthly:{
                 plan_id:"price_1MwfmmSFnJmyrDL83cjjAgEF",
                 document_limit:500,
                 query_limit:100000,
                 inr_plan_id:"price_1MzEXMSFnJmyrDL8hPlv7l9U",
              },
              elite_monthly:{
                 plan_id:"",
                 document_limit:20000,
                 query_limit:200000
              }
         },
         6:{
            basic:{
               document_limit:10,
               query_limit:1000
              },
              standard_monthly:{
               plan_id:"price_1MsiQfSFnJmyrDL86CNgNgZO",
               document_limit:50,
               query_limit:10000,
               inr_plan_id:"price_1MzEVcSFnJmyrDL8x5veZxHm",
              },
              growth_monthly:{
               plan_id:"price_1MsiO5SFnJmyrDL8AfTIPyl1",
               document_limit:250,
               query_limit:50000,
               inr_plan_id:"price_1MzEWFSFnJmyrDL8sGi2XGq2",
              },
              professional_monthly:{
                 plan_id:"price_1MwfmmSFnJmyrDL83cjjAgEF",
                 document_limit:500,
                 query_limit:100000,
                 inr_plan_id:"price_1MzEXMSFnJmyrDL8hPlv7l9U",
              },
              elite_monthly:{
                 plan_id:"",
                 document_limit:20000,
                 query_limit:200000
              }
         }
      }
   }
}